### ISSUE TITLE
npm run build error, routes clashing

### ISSUE THREAD

**Issue by edelah** [mistlog/sapper-template#3]
When I run the command 'npm run build' , i get this error:

> sapper build --legacy

> Building...
[1m[31m> **The index.css and index.tsx routes clash**[22m[39m
[90mError: The index.css and index.tsx routes clash
    at server_routes.forEach.route (/root/code/webhn2/node_modules/sapper/dist/core.js:1410:10)
    at Array.forEach (<anonymous>)
    at Object.create_manifest_data (/root/code/webhn2/node_modules/sapper/dist/core.js:1406:16)
    at build (/root/code/webhn2/node_modules/sapper/dist/build.js:68:29)
    at _build (/root/code/webhn2/node_modules/sapper/dist/cli.js:698:8)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:777:11)
    at executeUserCode (internal/bootstrap/node.js:499:15)
    at startMainThreadExecution (internal/bootstrap/node.js:436:3)[39m

**Comment by mistlog** [comment]
Thanks for reporting this, I fixed it by adding "--ext" option in `npm script: build`.

**Comment by mistlog** [comment]
I verified that the fix worked for me. Reopen the issue, if you still have problems.
